package com.camoutech.navigationintent.datas

import com.camoutech.navigationintent.model.Word

class Dictionnary {

    fun datas(): List<Word> {
        return listOf(
            Word("Agachon", "être à l’agachon, c’est être à l’affût "),
            Word("Aïoli","façon de dire bonjour ou au revoir. “Aïoli les amis !"),
            Word("Alibófi", "testicules"),
            Word("An pèbre", "une époque passée ou future mais qu’on ne sait pas vraiment définir"),
            Word("Arapède", "personne collante, pot de colle quoi !"),
            Word("Arranger", "se mettre d’accord"),
            Word("Bader", "regarder stupidement, bouche bée ou admirer"),
            Word("Balès", "costaud, vient sans doute du mot Balaise"),
            Word("Balètti", "c’est le bal populaire, la soirée dansante. Aujourd’hui, quand on va au Balètti c’est qu’on va voir un concert du Massilia Souns System !"),
            Word("Ballon", "football. Et oui, ici on joue au ballon !"),
            Word("Baou", "sommet rocheux d’une colline"),
            Word("Barjaquer", "bavarder"),
            Word("Bastonner", "se battre"),
            Word("Belsunce (arriver comme)", "Arriver chez quelqu’un les mains vides"),
            Word("Bestiasse", "personne stupide"),
            Word("Bras-cassé", "paresseux ou maladroit"),
            Word("Brèle", "nul"),
            Word("Cacou", "Personne qui en fait trop, snobinard, petit malin qui se fait remarquer"),
            Word("Cafi", "Plein, rempli"),
            Word("Cafoutchi", "cagibi, petite pièce"),
            Word("Cagade", "grosse bêtise ou gaffe"),
            Word("Cagagne", "diarrhée"),
            Word("Caganis", "le dernier né d’une famille"),
            Word("Cagnard", "soleil et chaleur, ou espace découvert en plein soleil"),
            Word("Cagole", "fille de petite vertu, avec mauvais genre, morue, poissonnière"),
            Word("Caguer", "Ben, aller aux toilettes pour la grosse commission !"),
            Word("Collègue", "ami"),
            Word("Commission", "faire les commissions signifie faire les courses"),
            Word("Dégun", "personne. “Y a dégun ici !”"),
            Word("D’équerre", "ivre, mais alors vraiment beaucoup !"),
            Word("Emboucaner", "infecter, puer ou alors chercher la bagarre"),
            Word("Encaper", "avoir de la chance"),
            Word("Escagassé", "fatigué, agacé, exaspéré"),
            Word("Escamper (s’)", "fuir, décamper"),
            Word("Esque", "petit vers servant d’appât de pêche"),
            Word("Esquichés", "serrés, entassés"),
            Word("Estrasse", "tenue vestimentaire d’une personne peu élégante et soignée"),
            Word("Fada", "fou"),
            Word("Figure (n’avoir pas de)", "agir dans le sens tout à fait contraire à l’honneur"),
            Word("Fly", "pastis, aussi appelé Jaune. “Sert le jaune collègue !”"),
            Word("Gabian", "Mouette, oiseau marseillais"),
            Word("Gansailler", "secouer physiquement ou moralement"),
            Word("Galéjade", "plaisanterie, petite blague sans conséquence"),
            Word("Glandouiller", "ne rien faire"),
            Word("Gobi", "petit poisson aux gros yeux"),
            Word("Grognasse", "femme désagréable"),
            Word("Jobastre", "personne un peu folle qui prend des risques"),
            Word("Languir", "souffrir de l’absence ou s’ennuyer"),
            Word("Maffre", "postérieur – cul"),
            Word("Maï", "encore"),
            Word("Mariolle", "faire le mariolle, c’est faire le rigolo"),
            Word("Marroner", "rouspéter, râler"),
            Word("Mastre", "personne sans grand intérêt, pauvre type"),
            Word("Méfi", "Attention !"),
            Word("Minot", "enfant, gamin"),
            Word("Morfale", "affamé, mort de faim"),
            Word("Morfler", "recevoir une raclée"),
            Word("Moulon", "tas, amas (c’est jamais très bon de se retrouver sous un moulon !)"),
            Word("Néguer", "se noyer"),
            Word("Pachole", "sexe féminin"),
            Word("Pacoulin", "plouc ou type de la campagne profonde"),
            Word("Palot (rouler un)", "embrasser goulûment"),
            Word("Panade (être dans la)", "avoir de gros ennuis"),
            Word("Papé, Papet", "grand-père ou vieil homme avec notion de respect"),
            Word("Pastisser", "salir"),
            Word("Péguer", "coller"),
            Word("Pièce", "passer la pièce signifie passer la serpillère"),
            Word("Pile", "la pile c’est l’évier en provençal"),
            Word("Ravan", "Objet en mauvais état et vieux, souvent employé pour une vieille voiture"),
            Word("Ravi", "personne toujours contente (dans la crèche provençale, le santon du Ravi occupe une place importante)"),
            Word("Rouste", "raclée"),
            Word("Ruiner (se)", "se faire mal"),
            Word("Scoumoune", "malchance (avoir la scoumoune c’est pas le top…)"),
            Word("Stassi", "bon à rien (souvent on dit, espèce de Stassi !)"),
            Word("Stoquefiche", "personne très maigre"),
            Word("Tarpin", "beaucoup, très"),
            Word("Tè, vé", "tiens, regarde !"),
            Word("Testard", "personne têtue"),
            Word("Toti", "imbécile"),
            Word("Tron de l’air", "personne vive et énergique"),
            Word("Wagon", "grand nombre, beaucoup (c’est rarement bon signe quand l’OM se prend un wagon…)"),
            Word("Zoù", "allez, ça y est"),
            Word("Zoù maï", "ça recommence!")
        )
    }
}